# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "linuxchina/buildpack-deno"
version = "0.2.0"
name = "Deno Buildpack"
homepage = "https://github.com/linux-china/buildpack-deno"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[metadata]
include-files = [
  "LICENSE",
  "README.md",
  "buildpack.toml"
]
